[book]
authors = ["andrew"]
language = "en"
multilingual = false
src = "src"
title = "test-book"


[output.html]
additional-css = ["mdbook_plugin/visualization.css"]
additional-js = ["mdbook_plugin/helpers.js", "mdbook_plugin/book.js"]